-- ====================================================================
-- COSC 2409: Full Kaggle Dataset Staging Schema (53 Columns)
-- ====================================================================

DROP TABLE IF EXISTS raw_staging;

CREATE TABLE raw_staging (
    type VARCHAR(50),
    days_for_shipping_real INT,
    days_for_shipment_scheduled INT,
    benefit_per_order DECIMAL(10,2),
    sales_per_customer DECIMAL(10,2),
    delivery_status VARCHAR(100),
    late_delivery_risk INT,
    category_id INT,
    category_name VARCHAR(100),
    customer_city VARCHAR(100),
    customer_country VARCHAR(100),
    customer_email VARCHAR(100),
    customer_fname VARCHAR(100),
    customer_id INT,
    customer_lname VARCHAR(100),
    customer_password VARCHAR(100),
    customer_segment VARCHAR(100),
    customer_state VARCHAR(100),
    customer_street VARCHAR(255),
    customer_zipcode VARCHAR(50),
    department_id INT,
    department_name VARCHAR(100),
    latitude DECIMAL(10,6),
    longitude DECIMAL(10,6),
    market VARCHAR(100),
    order_city VARCHAR(100),
    order_country VARCHAR(100),
    order_customer_id INT,
    order_date_dateorders VARCHAR(100),
    order_id INT,
    order_item_cardprod_id INT,
    order_item_discount DECIMAL(10,2),
    order_item_discount_rate DECIMAL(10,2),
    order_item_id INT,
    order_item_product_price DECIMAL(10,2),
    order_item_profit_ratio DECIMAL(10,2),
    order_item_quantity INT,
    sales DECIMAL(10,2),
    order_item_total DECIMAL(10,2),
    order_profit_per_order DECIMAL(10,2),
    order_region VARCHAR(100),
    order_state VARCHAR(100),
    order_status VARCHAR(100),
    order_zipcode VARCHAR(50),
    product_card_id INT,
    product_category_id INT,
    product_description TEXT,
    product_image VARCHAR(255),
    product_name VARCHAR(255),
    product_price DECIMAL(10,2),
    product_status INT,
    shipping_date_dateorders VARCHAR(100),
    shipping_mode VARCHAR(100)
);