"""
Automated Intake Scanner & Course Plan Scaffolder
Scans the knowledge_dump/ drop zones, catalogs incoming assets,
and generates a structured draft course plan.
"""

import os
import sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KNOWLEDGE_DIR = os.path.join(BASE_DIR, "knowledge_dump")

DROP_ZONES = [
    "raw_syllabi",
    "legacy_decks",
    "lecture_notes_and_transcripts",
    "reference_literature",
    "ideas_and_brainstorms"
]


def scan_knowledge_dump():
    print("=" * 70)
    print("COURSE CREATION TEMPLATE: KNOWLEDGE DUMP INTAKE SCANNER")
    print("=" * 70)

    if not os.path.exists(KNOWLEDGE_DIR):
        print(f"[FAIL] Knowledge dump directory not found at: {KNOWLEDGE_DIR}")
        return 1

    manifest_path = os.path.join(KNOWLEDGE_DIR, "intake_manifest.yaml")
    has_manifest = os.path.exists(manifest_path)
    print(f"Intake Manifest Detected: {'[PASS]' if has_manifest else '[WARN] (intake_manifest.yaml missing)'}")

    inventory = {}
    total_files = 0
    for zone in DROP_ZONES:
        zone_path = os.path.join(KNOWLEDGE_DIR, zone)
        if os.path.exists(zone_path):
            files = [f for f in os.listdir(zone_path) if not f.startswith(".")]
            inventory[zone] = files
            total_files += len(files)
            print(f"  - {zone:<32}: {len(files):>2} files detected")
        else:
            inventory[zone] = []
            print(f"  - {zone:<32}: Directory missing")

    print(f"\nTotal Intake Assets Inventoried: {total_files} files")

    # Generate scaffolded course plan markdown
    scaffold_path = os.path.join(BASE_DIR, "scaffolded_course_plan.md")
    with open(scaffold_path, "w", encoding="utf-8") as f:
        f.write("# Scaffolded Course Plan & Intake Inventory\n")
        f.write(f"**Generated by Intake Scanner:** {os.path.basename(scaffold_path)}\n\n")
        f.write("## 1. Intake Drop Zone Inventory\n")
        for zone, files in inventory.items():
            f.write(f"### `{zone}/` ({len(files)} files)\n")
            if files:
                for f_name in files:
                    f.write(f"- `{f_name}`\n")
            else:
                f.write("- *No files currently staged in this drop zone.*\n")
            f.write("\n")

        f.write("## 2. Recommended Next Steps\n")
        f.write("1. Review `course_creation_template/config.py` to customize institutional branding.\n")
        f.write("2. Use `templates/competency_map_template.md` to map out the weekly competencies.\n")
        f.write("3. Use `scripts/generate_deck.py` with `playbooks/slide_design_playbook.md` to build slides.\n")
        f.write("4. Run `scripts/audit_deck.py` to verify slide deck compliance before delivery.\n")

    print(f"\n[PASS] Scaffolded plan generated at: '{scaffold_path}'")
    print("=" * 70)
    return 0


if __name__ == "__main__":
    sys.exit(scan_knowledge_dump())
