/*
====================================================================
Module 4: Aggregation, Set Operations, and Pivoting
====================================================================
File: week_4_grouping_sets_lab.sql
Focus: GROUP BY, HAVING, UNION, and Conditional Aggregation.
====================================================================
*/

/* --- INSTRUCTOR DEMONSTRATION --- */

-- Demo 1: Basic Aggregation
-- Count how many employees are in each department.
SELECT department, COUNT(employee_id) AS total_employees
FROM employees
GROUP BY department;

-- Demo 2: UNION Operator
-- Combine lists of specific products and specific locations into a single review list.
SELECT product_name AS item_name, 'Product' AS category_type FROM products WHERE retail_price > 200
UNION ALL
SELECT city, 'Location' FROM locations;

/* --- STUDENT ASSESSMENT --- */

-- 1. Calculate the total stock quantity for each product category.
SELECT category, SUM(stock_quantity) AS total_stock
FROM products
GROUP BY category;

-- 2. Find the average salary per department, but ONLY show departments 
-- where the average salary is strictly greater than $80,000. (Use HAVING).
SELECT department, AVG(salary) AS avg_salary
FROM employees
GROUP BY department
HAVING AVG(salary) > 80000;

-- 3. Calculate the total gross revenue generated by each order.
-- (Hint: Join orders to order_lines, multiply quantity by unit_price, and SUM).
SELECT o.order_id, o.order_date, SUM(ol.quantity * ol.unit_price) AS order_total
FROM orders o
INNER JOIN order_lines ol ON o.order_id = ol.order_id
GROUP BY o.order_id, o.order_date
ORDER BY order_total DESC;

-- 4. Pivot Challenge: Use conditional aggregation (CASE inside SUM) 
-- to show total stock quantity separated by 'Gaming', 'Fitness', and 'Outdoor' in single columns.
SELECT 
    SUM(CASE WHEN category = 'Gaming' THEN stock_quantity ELSE 0 END) AS gaming_stock,
    SUM(CASE WHEN category = 'Fitness' THEN stock_quantity ELSE 0 END) AS fitness_stock,
    SUM(CASE WHEN category = 'Outdoor' THEN stock_quantity ELSE 0 END) AS outdoor_stock
FROM products;