/*
====================================================================
Module 4: Aggregation, Set Operations, and Pivoting
File: week_4_grouping_sets_lab.sql
Focus: GROUP BY, HAVING, UNION, and Conditional Aggregation.
====================================================================
*/

/* 
--------------------------------------------------------------------
Part 1: Instructor Demonstration Queries
Use these during Periods 1 & 2 to explain aggregation mechanics.
--------------------------------------------------------------------
*/

-- Demo 1: Basic Aggregation and Grouping
-- Goal: Count how many employees work in each department.
SELECT 
    department, 
    COUNT(employee_id) AS total_employees
FROM employees
GROUP BY department
ORDER BY total_employees DESC;

-- Demo 2: Group-Level Filtering with HAVING
-- Goal: Find the average salary per department, but only show departments 
-- where the average salary is strictly greater than $80,000.
SELECT 
    department, 
    AVG(salary) AS avg_salary
FROM employees
GROUP BY department
HAVING AVG(salary) > 80000;

-- Demo 3: The UNION Operator
-- Goal: Combine completely different datasets into a single result set 
-- for an "Archived Entities" report. Columns must align exactly.
SELECT 
    product_name AS entity_name, 
    'Discontinued Product' AS entity_type 
FROM products 
WHERE discontinued_date IS NOT NULL
UNION
SELECT 
    first_name || ' ' || last_name AS entity_name, 
    'Former Employee' AS entity_type 
FROM employees 
WHERE is_active = FALSE;


/* 
--------------------------------------------------------------------
Part 2: Student Assessment (Business Reporting Lab)
Periods 3 & 4 Independent Practice
--------------------------------------------------------------------
*/

-- 1. Write a query to calculate the total stock quantity for each product category.
-- Order the results from highest total stock to lowest.
SELECT 
    category, 
    SUM(stock_quantity) AS total_stock
FROM products
GROUP BY category
ORDER BY total_stock DESC;

-- 2. Write a query to find the maximum and minimum retail prices within each category.
-- Exclude any categories where the maximum price is less than $50.
SELECT 
    category, 
    MAX(retail_price) AS highest_price,
    MIN(retail_price) AS lowest_price
FROM products
GROUP BY category
HAVING MAX(retail_price) >= 50.00;

-- 3. Calculate the total gross revenue generated by each specific order.
-- You will need to join orders to order_lines, multiply quantity by unit_price, 
-- and SUM the result. Group by the order_id and order_date.
SELECT 
    o.order_id, 
    o.order_date, 
    SUM(ol.quantity * ol.unit_price) AS total_revenue
FROM orders o
INNER JOIN order_lines ol ON o.order_id = ol.order_id
GROUP BY o.order_id, o.order_date
ORDER BY total_revenue DESC;

-- 4. Find the total number of items sold per product category.
-- This requires joining products, order_lines, and orders, then grouping by category.
SELECT 
    p.category,
    SUM(ol.quantity) AS items_sold
FROM products p
INNER JOIN order_lines ol ON p.product_id = ol.product_id
GROUP BY p.category
ORDER BY items_sold DESC;

-- 5. Set Operations: The marketing team needs a single mailing list of all locations.
-- Write a UNION query that combines the city and state from the locations table 
-- with a concatenated "city, state" string (e.g., 'Topeka, KS') manually hardcoded 
-- for two prospective new locations: 'Omaha, NE' and 'Boise, ID'.
SELECT city, state 
FROM locations
UNION
SELECT 'Omaha', 'NE'
UNION
SELECT 'Boise', 'ID';

-- 6. The Pivot Challenge: Use conditional aggregation (a CASE statement inside a SUM function) 
-- to show total stock quantities separated by 'Gaming', 'Fitness', and 'Outdoor' in single columns.
-- This flattens row data into column data.
SELECT 
    SUM(CASE WHEN category = 'Gaming' THEN stock_quantity ELSE 0 END) AS gaming_stock,
    SUM(CASE WHEN category = 'Fitness' THEN stock_quantity ELSE 0 END) AS fitness_stock,
    SUM(CASE WHEN category = 'Outdoor' THEN stock_quantity ELSE 0 END) AS outdoor_stock
FROM products;